version: '3.8'

services:
  filepatrol-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filepatrol-builder
    working_dir: /app
    volumes:
      - ../:/app/
    environment:
      - CGO_ENABLED=1
    entrypoint: [ "/bin/sh", "-c" ]
    command: /app/docker/entrypoint.sh
